staging_yoda_url=https://staging-mryoda.yodaprojects.com/
dev_yoda_url=https://dev-mryoda.yodaprojects.com/


#dev_dlw_url=https://dev-dlw.labsquire.com/
#dev_url=https://dev-microgen.labsquire.com/
#staging_mic_url=https://staging-microgen.labsquire.com/
excel.filePath=src/test/resources/TestData/MrYodaStaging.xlsx
excel.sheetName=Diagnostics
excel.sheetName_dna=DNADecoder
excel.rowNum=1
